### ISSUE TITLE
calling global ZSTD_getErrorName

### ISSUE THREAD

**Issue by stuta** [sjnam/luajit-zstd#3]
I think you should fix:

return nil, "ZSTD_decompressStream() error: "
            ..ZSTD_getErrorName(rlen)
=>
return nil, "ZSTD_decompressStream() error: "
            ..zstd.ZSTD_getErrorName(rlen)

**Comment by sjnam** [comment]
@stuta 
Thank you.
4380a60b6392ba152bdca221dd0e55e03becf257
